version: "3.3"

services:
  booking_pgsql:
    build: ./docker/postgres/
    restart: always
    env_file:
      - docker/config/db.env
    ports:
      - "5432:5432"
    networks:
      - book_network

  booking_app:
    build: .
    depends_on:
      - booking_pgsql
    restart: always
    ports:
      - "8080:8080"
    networks:
      - book_network

networks:
  book_network:
    driver: bridge