spring:
  datasource:
    url: jdbc:postgresql://booking_pgsql:5432/booking
    username: postgres
    password: booking
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
